baseURL = "https://abianji.com/"
languageCode = "en"
title = "阿比安吉"
theme = "bilberry-hugo-theme"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
buildDrafts = true

# Disqus Username
disqusShortname = "abianji"

# Google Analytics UA number
# googleAnalytics = "UA-123564234-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "标签"
  weight = 20
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Ritchie Zhu"
  avatar = "/img/avatar.jpg"
  seotitle = "阿比安吉"
  subtitle = "生活本来就是一点一滴"
  description = "note for life and study"
  paginate = 10

  # Choose your social networks
  email = "liusong850315@gmail.com"
  github = "liseen315"
  # twitter = "twitter_username"
  # linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
   codepen = "liseen"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  changyan = false
  changyanId = "cyt3toRiB"
  changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "xxx"